[package]
name = "cutblanc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
hound = "3.5.1"
minimp3 = { version = "0.5.1", features = ["async_tokio"] }

